create or replace PROCEDURE MM_GETUSERS (C_USERS OUT SYS_REFCURSOR )AS 
BEGIN
    OPEN C_USERS FOR 
    SELECT * FROM  MM_USER u where estado<> 'N';
END MM_GETUSERS;

create or replace PROCEDURE MM_GETROLES
(
    C_ROLES OUT SYS_REFCURSOR
)
AS 
BEGIN
    OPEN C_ROLES FOR
    SELECT * FROM MM_ROLE WHERE ESTADO<>'N'
    ORDER BY ID_ROLE;
END MM_GETROLES;

